### ISSUE TITLE
`Writer` rejects info dict with `physical` key

### ISSUE THREAD

**Issue by drj11** [drj11/pypng#103]
A PNG with a `pHYs` chunk will generate (when read) an `info` dict that has a `physical` key.

Passing this to a `Writer` fails though:
```
drj@cha:~/prj/pypng$ python3 code/pipcat alert.png 
Traceback (most recent call last):
  File "code/pipcat", line 47, in <module>
    main(sys.argv)
  File "code/pipcat", line 44, in main
    return cat(png.binary_stdout(), [open(n, 'rb') for n in argv[1:]])
  File "code/pipcat", line 37, in cat
    w = png.Writer(width, height, **tinfo)
TypeError: __init__() got an unexpected keyword argument 'physical'
```

**Comment by drj11** [comment]
Now that `prichunkpng` can add a `pHYs` chunk, and `pipcat` takes stdin as an argument, we can reproduce the error using no files and a pipeline that uses only PyPNG tools:

    priforgepng grl | prichunkpng --physical 72dpi - | python3 code/pipcat -

Gives the error:

```
Traceback (most recent call last):
  File "/Users/drj/prj/pypng/code/pipcat", line 54, in <module>
    main(sys.argv)
  File "/Users/drj/prj/pypng/code/pipcat", line 51, in main
    return cat(png.binary_stdout(), [png.cli_open(n) for n in argv[1:]])
  File "/Users/drj/prj/pypng/code/pipcat", line 44, in cat
    w = png.Writer(width, height, **tinfo)
TypeError: __init__() got an unexpected keyword argument 'physical'
```
