### ISSUE TITLE
png.Reader not guessing bytes

### ISSUE THREAD

**Issue by Mulac** [drj11/pypng#118]
The docs says Reader.__init__ takes bytes but fails on the isinstance(some_bytes, array) check.

Is this expected behaviour?
```
>>> import png
>>> png.Reader("tests/doop.png")
<png.Reader object at 0x7fd48d3cf100>
>>> with open("tests/doop.png", 'rb') as f:
...     png.Reader(f.read())
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/calum/.cache/pypoetry/virtualenvs/hsi-ZCFKj1YC-py3.10/lib/python3.10/site-packages/png.py", line 1375, in __init__
    raise ProtocolError("expecting filename, file or bytes array")
png.ProtocolError: ProtocolError: expecting filename, file or bytes array
```

**Comment by drj11** [comment]
The design predates the type `bytes` (it's from early Python 2, and possibly Python 1.5.2), so it only works on `array.array("B")`.

However, i can see that `png.Reader(f.read())` could be useful, so i shall consider this a bug.

`png.Reader(f)` should work by the way; although it does then become unclear when you should close `f`.
