### ISSUE TITLE
Writer.write_packed raises TypeError

### ISSUE THREAD

**Issue by cmdneo** [drj11/pypng#98]
`Writer.write_packed` raises `TypeError` when used.

Data format:
```
[
    [[r, g, b], [r, g, b], [r, g, b], [r, g, b]],
    [[r, g, b], [r, g, b], [r, g, b], [r, g, b]],
    [[r, g, b], [r, g, b], [r, g, b], [r, g, b]]
]
```

Code used:
```python
import png
from random import randint

def main():
    size = [1200, 800]
    filename = f"{randint(0, 2**16)}.png"
    wrt = png.Writer(size[0], size[1], greyscale=False)
    data = [[[0, 0, 0] for x in range(size[0])] for y in range(size[1])]

    with open(filename, "wb") as f:
        wrt.write_packed(f, data)

main()
```

Traceback:
```
$ python img-gen.py
Traceback (most recent call last):
  File "img-gen.py", line 23, in <module>
    main()
  File "img-gen.py", line 20, in main
    wrt.write_packed(f, data)
  File "/usr/lib/python3.8/site-packages/png.py", line 745, in write_packed
    data.extend(row)
TypeError: 'list' object cannot be interpreted as an integer
```

Version info:
```
pip        19.3.1
pyparsing  2.4.6
pypng      0.0.20
python 3.8.0
```

**Comment by drj11** [comment]
- You probably shouldn't be using `write_packed()`;
- `write_packed()` takes an [iterator that yields each row where each row is a sequence of bytes](https://github.com/drj11/pypng/blob/main/code/png.py#L707)—you are passing an iterator that yields each row as a list of lists.
- therefore you should use `write()` and flatten each row:

I have modified your example to make the `flat_rows` sequence, where each row is a single linear list:

```
import itertools
import png
from random import randint

def main():
    size = [1200, 800]
    filename = f"{randint(0, 2**16)}.png"
    wrt = png.Writer(size[0], size[1], greyscale=False)
    data = [[[0, 0, 0] for x in range(size[0])] for y in range(size[1])]

    flat_rows = [itertools.chain(*row) for row in data]

    with open(filename, "wb") as f:
        wrt.write(f, flat_rows)

main()
```
